stages:
  filter:
    cmd: >-
      python pipeline/filter.py
      --threshold=${filter.threshold}
      --keep_null=${filter.keep_null}
      data/raw/smiles.tsv.gz
      data/raw/activities.tsv.gz
      data/filtered/filtered.csv
    deps:
      - data/raw/activities.tsv.gz
      - data/raw/smiles.tsv.gz
      - pipeline/filter.py
    outs:
      - data/filtered
  
  split:
    cmd: >-
      python pipeline/split.py
      --test_ratio=${split.test_ratio}
      --val_ratio=${split.val_ratio}
      --homology_based ${split.homology_based}
      --random_seed ${split.random_seed}
      data/filtered/filtered.csv
      data/splitted
    deps:
      - data/filtered
      - pipeline/split.py
    outs:
      - data/splitted
  
  featurize_topological_fp:
    cmd: >-
      python pipeline/featurize_topological_fp.py
      data/splitted
      data/features/fingerprints/topological
    deps:
      - data/splitted
      - pipeline/featurize_topological_fp.py
    outs:
      - data/features/fingerprints/topological

  featurize_morgan_fp:
    cmd: >-
      python pipeline/featurize_morgan_fp.py
      --radius=${featurize_morgan_fp.radius}
      --n_bits=${featurize_morgan_fp.n_bits}
      data/splitted
      data/features/fingerprints/morgan
    deps:
      - data/splitted
      - pipeline/featurize_morgan_fp.py
    outs:
      - data/features/fingerprints/morgan
  
  featurize_maccs_fp:
    cmd: >-
      python pipeline/featurize_maccs_fp.py
      data/splitted
      data/features/fingerprints/maccs
    deps:
      - data/splitted
      - pipeline/featurize_maccs_fp.py
    outs:
      - data/features/fingerprints/maccs
  
  train_gb_topological_fp:
    cmd: >-
      python pipeline/train_gb.py
      --subsample=${train_gb.subsample}
      data/features/fingerprints/topological/train.npz
      models/gb_topological_fp/model.pkl
    deps:
      - data/features/fingerprints/topological/train.npz
      - pipeline/train_gb.py
    outs:
      - models/gb_topological_fp/model.pkl

  train_gb_morgan_fp:
    cmd: >-
      python pipeline/train_gb.py
      --subsample=${train_gb.subsample}
      data/features/fingerprints/morgan/train.npz
      models/gb_morgan_fp/model.pkl
    deps:
      - data/features/fingerprints/morgan/train.npz
      - pipeline/train_gb.py
    outs:
      - models/gb_morgan_fp/model.pkl

  train_gb_maccs_fp:
    cmd: >-
      python pipeline/train_gb.py
      --subsample=${train_gb.subsample}
      --use_weights=${train_gb.use_weights}
      data/features/fingerprints/maccs/train.npz
      models/gb_maccs_fp/model.pkl
    deps:
      - data/features/fingerprints/maccs/train.npz
      - pipeline/train_gb.py
    outs:
      - models/gb_maccs_fp/model.pkl
    
    