filter:
  threshold: 8.0
  keep_null: true

split:
  test_ratio: 0.2  # test subset ratio of the all data
  val_ratio: 0.1  # validation subset ratio of the all dataset without the test data
  homology_based: false
  random_seed: 228

featurize_morgan_fp:
  radius: 2
  n_bits: 1024

featurize_voxels:

train_gb:
  subsample: 0.1
  