filter:
  threshold: 8.0
  keep_null: true

split:
  test_ratio: 0.2  # test subset ratio of the all data
  val_ratio: 0.1  # validation subset ratio of the all dataset without the test data
  homology_based: False
  random_seed: 228

feature_extraction:
  type: topological



