filter:
  # Minimal value to consider a ligand to be active
  threshold: 8.0

  # Keep molecules with null affinity value. Consider null molecules as not active, if true
  keep_null: true


split:
  # Ratio of the test split (of the all filtered dataset)
  test_ratio: 0.2

  # Ratio of the validation split (of the filtered dataset without test data)
  val_ratio: 0.1

  # Split clusters of similar molecules instead of single molecules, if true
  homology_based: true

  random_seed: 228


featurize_morgan_fp:
  # Radius of Morgan fingerprints
  radius: 2

  # Number of bit of a fingerprint
  n_bits: 1024


train_gb:
  # Fraction of samples used for fitting a single tree
  subsample: 0.3

  # The number of boosting stages to perform
  n_estimators: 300

  # The maximum depth of the individual regression estimators
  max_depth: 3

  # Use weighted loss. Use it if you have unbalanced dataset
  use_weights: true


generate_voxels:
  box_size_x: 15
  box_size_y: 15
  box_size_z: 15
  voxel_size: 0.5

train_cnn:
  batch_size: 32
  learning_rate: 1e-3
  l2_lambda: 0.04
  dropout: 0.4
  seed: 228